name: Kube Lint
on:
  pull_request:
    paths:
      - deployments/*

jobs:
  kube-linter:
    name: chart-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: deployments
