name: Git Commit Lint
on:
  workflow_call:
    inputs:
      configFile:
        required: false
        type: string
        default: ./.commitlintrc.yml

jobs:
  commitlint:
    name: commit-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ${{ inputs.configFile }}
