name: Lint an OpenAPI spec with inso
on:
  workflow_call:
    inputs:
      specLocation:
        description: The filepath to the openapi spec.
        required: true
        type: string

jobs:
  openapi-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: kong/setup-inso@v1
        with:
            inso-version: 3.5.0
      - name: Lint OpenAPI spec
        run: inso lint spec "${{ inputs.specLocation }}"
