name: Openapi Generate PHP Client
on:
  workflow_call:
    inputs:
      phpVersion:
        required: false
        type: string
        default: "8.3"
      specLocation:
        description: The filepath to the openapi spec.
        required: false
        type: string
        default: openapi.yaml
      configLocation:
        description: The filepath to the openapi config file.
        required: true
        type: string
      templateLocation:
        description: The path to the openapi template directory.
        required: false
        type: string
      payload:
        description: The base64 encoded openapi spec. Written to the spec filepath if present.
        required: false
        type: string
      version:
        description: The openapi generator version used.
        required: false
        type: string
        default: v5.4.0
      organization:
        description: The organization to use when generating the client.
        required: false
        type: string
        default: ${{ github.repository_owner }}
      release:
        description: The ID of the release where the spec asset is located.
        required: false
        type: string
      repository:
        description: The repository that triggered the client generation.
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove Generated Files
        continue-on-error: true
        run: xargs -I{} rm -rf "{}" < .openapi-generator/FILES
      - name: Download Release Asset
        uses: dsaltares/fetch-gh-release-asset@master
        if: "${{ inputs.release != '' }}"
        with:
          repo: ${{ inputs.repository }}
          version: ${{ inputs.release }}
          file: ${{ inputs.specLocation }}
          target: ${{ inputs.specLocation }}
          token: ${{ secrets.token }}
      - name: Write Spec
        run: |
          if [[ ! -z "${{ inputs.payload }}" ]]
          then
            echo "${{ inputs.payload }}" | base64 --decode > ${{ inputs.specLocation }}
          fi
          cat ${{ inputs.specLocation }}
      - name: Read Spec
        id: spec
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: ${{ inputs.specLocation }}
          title: info.title
          version: info.version
      - name: Set Template Dir
        id: set-template
        if: ${{ inputs.templateLocation }}
        run: |
          echo 'OPENAPI_TEMPLATE=-t ${{ inputs.templateLocation }}' >> $GITHUB_OUTPUT
      - name: Generate PHP Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          generator-tag: ${{ inputs.version }}
          openapi-file: ${{ inputs.specLocation }}
          config-file: ${{ inputs.configLocation }}
          command-args: |
            --git-user-id ${{ inputs.organization }} --git-repo-id ${{ github.event.repository.name }} \
            ${{ steps.set-template.outputs.OPENAPI_TEMPLATE }} \
            -o .
      - name: Remove Spec
        run: rm -f ${{ inputs.specLocation }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.phpVersion }}
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: php vendor/bin/phpunit --no-coverage test/
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "${{ steps.spec.outputs.title }} ${{ steps.spec.outputs.version }}"
          tag: ${{ steps.spec.outputs.version }}
