name: Openapi Generate PHP Client
on:
  workflow_call:
    inputs:
      specLocation:
        description: The filepath to the openapi spec.
        required: false
        type: string
        default: openapi.yaml
      configLocation:
        description: The filepath to the openapi config file.
        required: false
        type: string
      templateLocation:
        description: The path to the openapi template directory.
        required: false
        type: string
      payload:
        description: The base64 encoded openapi spec. Written to the spec filepath if present.
        required: false
        type: string
      version:
        description: The openapi generator version used.
        required: false
        type: string
        default: v5.2.0
      organization:
        description: The organization to use when generating the client.
        required: false
        type: string
        default: $${{ github.repository_owner }}
      package:
        description: The name of the package to generate the code in.
        required: true
        type: string
      options:
        description: Additional options passed to the generator command.
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove Generated Files
        continue-on-error: true
        run: xargs -I{} rm -rf "{}" < .openapi-generator/FILES
      - name: Write Spec
        run: |
          mkdir -p api
          if [[ ! -z "${{ inputs.payload }}" ]]
          then
            echo "${{ inputs.payload }}" | base64 --decode > ${{ inputs.specLocation }}
          fi
          cat ${{ inputs.specLocation }}
      - name: Read Spec
        id: spec
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: ${{ inputs.specLocation }}
          title: info.title
          version: info.version
      - name: Generate PHP Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          generator-tag: ${{ inputs.version }}
          openapi-file: ${{ inputs.specLocation }}
          config-file: ${{ inputs.configLocation }}
          template-dir: ${{ inputs.templateLocation }}
          command-args: --git-user-id $${{ inputs.organization }} --git-repo-id ${{ github.event.repository.name }} --additional-properties=invokerPackage=${{ inputs.package }} ${{ inputs.options }} -o .
      - name: Remove Spec
        run: rm -f ${{ inputs.specLocation }}
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "${{ steps.spec.outputs.title }} ${{ steps.spec.outputs.version }}"
          tag: ${{ steps.spec.outputs.version }}
