name: Nginx Build and Push Image

on:
  workflow_call:
    inputs:
      ref:
        description: "The ref used to build the image."
        required: false
        type: string
        default: ""
      tag:
        description: "The tag to use for the image build."
        required: true
        type: string
      dockerfile:
        description: "Path to the application dockerfile you want to build."
        required: true
        type: string
      build_context:
        description: "Path to the build context."
        required: false
        type: string
        default: "."
    secrets:
      gh_token:
        required: true

jobs:
  build-proxy:
    name: Build Proxy Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}

      - name: Docker Build and Push Nginx
        uses: docker/build-push-action@v2
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nginx-${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max