name: PHP CS Fixer

on:
  workflow_call:
    inputs:
      php_version:
        description: "Required PHP version for this project."
        required: false
        type: string
        default: "8.2"
      command:
        description: "The command to run to for php-cs-fixer"
        required: false
        type: string
        default: "composer cs-fixer:lint"
    secrets:
      packagist_username:
        required: true
      packagist_password:
        required: true
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: PHP CS Fixer
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ inputs.php_version }}"
          tools: composer:v2

      - name: Cache PHP CS Fixer
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        env:
          COMPOSER_AUTH: |
            {
              "http-basic": {
                "repo.packagist.com": {
                  "username": "${{ secrets.packagist_username }}",
                  "password": "${{ secrets.packagist_password }}"
                }
              }
            }

      - name: Run PHP CS Fixer
        run: ${{ inputs.command }}
