name: PHP Unit Tests

on:
  workflow_call:
    inputs:
      php_version:
        required: false
        type: string
        default: "8.2"
      php_extensions:
        description: "Don't forget to add the default list if needed"
        required: false
        type: string
        default: "bcmath intl gd"
      test_command:
        default: "composer test"
      run_sonar:
        default: false
      coverage_file:
        default: "coverage.xml"
    secrets:
      packagist_username:
        required: true
      packagist_password:
        required: true
      github_token:
        required: false
      sonar_token:
        required: false
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: PHPUnit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          tools: composer, phpunit
          coverage: pcov
          extensions: ${{ inputs.php_extensions }}
        env:
          COMPOSER_AUTH_JSON: |
            {
              "http-basic": {
                "repo.packagist.com": {
                  "username": "${{ secrets.packagist_username }}",
                  "password": "${{ secrets.packagist_password }}"
                }
              }
            }
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: ${{ inputs.test_command }}
        env:
          COVERAGE_FILE: ${{ inputs.coverage_file }}
      - name: Fix code coverage paths
        if: "${{ inputs.run_sonar }}" == "true"
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' "${{ inputs.coverage_file }}"
      - name: SonarCloud Scan
        if: "${{ inputs.run_sonar }}" == "true"
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          SONAR_TOKEN: ${{ secrets.sonar_token }}
