name: PHP Syntax Check (lint)
on:
  workflow_call:
    inputs:
      php_version:
        required: false
        type: string
        default: "8.3"
    secrets:
      packagist_username:
        required: true
      packagist_password:
        required: true

jobs:
  php-lint:
    runs-on: ubuntu-latest
    name: PHP Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        coverage: none

    - name: Lint
      run: find . -name '*.php' -print0 | xargs -0 -n1 -P10 php -l
