name: PHP Build and Push Image

on:
  workflow_call:
    inputs:
      php_version:
        required: false
        type: string
        default: "7.4"
      ref:
        description: "The ref used to build the image."
        required: false
        type: string
        default: ""
      tag:
        description: "The tag to use for the image build."
        required: true
        type: string
      dockerfile:
        description: "Path to the application dockerfile you want to build."
        required: true
        type: string
      build_target:
        description: "The build target to use for the image build."
        required: false
        type: string
        default: "app"
    secrets:
      packagist_username:
        required: true
      packagist_password:
        required: true
      gh_token:
        required: true

jobs:
  build-app:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          tools: composer:v2
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader --apcu-autoloader
        env:
          COMPOSER_AUTH: >
            {
              "http-basic": {
                "repo.packagist.com": {
                  "username": "${{ secrets.packagist_username }}",
                  "password": "${{ secrets.packagist_password }}"
                }
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}

      - name: Docker Build and Push App
        uses: docker/build-push-action@v2
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          platforms: linux/amd64
          target: ${{ inputs.build_target }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max