name: PHP Unit Tests

on:
  workflow_call:
    inputs:
      php_version:
        required: false
        type: string
        default: "8.2"
      php_extensions:
        description: "Don't forget to add the default list if needed"
        required: false
        type: string
        default: "bcmath intl gd"
      test_command:
        type: string
        required: false
        default: "composer test"
      run_sonar:
        type: boolean
        required: false
        default: false
      coverage_file:
        type: string
        required: false
        default: "coverage.xml"
      coverage_artifact_name:
        type: string
        required: false
        default: "phpunit-code-coverage-report"
    secrets:
      packagist_username:
        required: true
      packagist_password:
        required: true
      sonar_token:
        required: false

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: PHPUnit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of Sonar reporting
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          tools: composer, phpunit
          coverage: pcov
          extensions: ${{ inputs.php_extensions }}
        env:
          COMPOSER_AUTH_JSON: |
            {
              "http-basic": {
                "repo.packagist.com": {
                  "username": "${{ secrets.packagist_username }}",
                  "password": "${{ secrets.packagist_password }}"
                }
              }
            }
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: |
          ${{ inputs.test_command }}
        env:
          COVERAGE_FILE: ${{ inputs.coverage_file }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.coverage_artifact_name }}
          path: ${{ inputs.coverage_file }}
          include-hidden-files: true
      - name: Fix code coverage paths
        if: ${{ inputs.run_sonar }}
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' "${{ inputs.coverage_file }}"
      - name: SonarCloud Scan
        if: ${{ inputs.run_sonar }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar_token }}
