name: PHPStan
on:
  workflow_call:
    inputs:
      php_version:
        required: false
        type: string
        default: "8.3"
      command:
        description: "The command to run to for phpstan"
        required: false
        type: string
        default: "composer phpstan"
      error_file:
        description: "The path to the error file to capture phpstan JSON errors"
        required: false
        type: string
        default: "phpstan-errors.json"
      artifact_name:
        description: "The name of the phpstan artifact"
        required: false
        type: string
        default: "phpstan-errors"
      cache_path:
        description: "The tmpDir path (i.e. ./.phpstan.cache)"
        required: false
        type: string
        default: "./.phpstan.cache"
    secrets:
      packagist_username:
        required: true
      packagist_password:
        required: true

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ inputs.php_version }}
          tools: composer
        env:
          COMPOSER_AUTH_JSON: |
            {
              "http-basic": {
                "repo.packagist.com": {
                  "username": "${{ secrets.packagist_username }}",
                  "password": "${{ secrets.packagist_password }}"
                }
              }
            }

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Cache PHPStan Results
        uses: actions/cache@v4
        with:
          path: ${{ inputs.cache_path }}
          key: "${{ runner.os }}-phpstan-${{ github.run_id }}" # always unique key - always writes a new cache
          restore-keys: |
            ${{ runner.os }}-phpstan-

      - name: Run PHPStan
        run: ${{ inputs.command }}
        env:
          PHPSTAN_ERROR_FILE: ${{ inputs.error_file }}

      - name: phpstan errors artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.error_file }}
          include-hidden-files: true
