name: Fix PHP Code Style
on:
  workflow_call:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: Laravel Pint Autofix
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache PHP CS Fixer
        uses: actions/cache@v4
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: none
      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.1.0
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(pint): fix code style issues"
