name: SonarCloud Scan

on:
  workflow_call:
    inputs:
      phpunit_coverage_file:
        type: string
        required: false
        default: "coverage.xml"
    secrets:
      sonar_token:
        required: false

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    name: SonarCloud Scan
    steps:
      # PHPUnit coverage paths in the coverage file need manually updated for SonarCloud
      # @see https://docs.sonarcloud.io/enriching/test-coverage/php-test-coverage/
      - name: Fix code coverage paths for SonarCloud
        run: |
          if [ -f "${{ inputs.phpunit_coverage_file }}" ]; then
            echo "PHPUnit coverage file found (${{ inputs.phpunit_coverage_file }})"
            sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' "${{ inputs.coverage_file }}"
          else
            echo "PHPUnit coverage file not found (${{ inputs.phpunit_coverage_file }})."
            echo "Skipping code coverage path fixes."
          fi
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar_token }}
